# Generated by Django 6.0.4 on 2026-04-09 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14)),
                ('horas_trabalhadas', models.TimeField(blank=True, null=True)),
                ('salario', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('horas', models.TimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='core.funcionario')),
            ],
        ),
    ]
